version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorld2021"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1odwjh0m3msn1"
s3_prefix = "HelloWorld2021"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=561744971673.dkr.ecr.us-east-1.amazonaws.com/helloworldrepo"]
